<?php

namespace ZIMZIM\ToolsBundle\Model;

use APY\DataGridBundle\Grid\Source\Entity;
use Doctrine\ORM\EntityRepository;
use ZIMZIM\ToolsBundle\Model\APYDataGrid\ApyDataGridRepositoryInterface;
use Symfony\Component\Security\Core\SecurityContext;

/**
 * UploadTinymceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadTinymceRepository extends EntityRepository implements ApyDataGridRepositoryInterface
{
    public function getList(Entity $source, SecurityContext $securityContext)
    {
        return $source;
    }
}
